services:
    app:
        build: .
        ports:
            - "8088:80"
        volumes:
            - ".:/var/www/html/"
            - "vendor:/var/www/html/vendor"
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mariadb:10.11
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./sql/import.sql:/docker-entrypoint-initdb.d/01-import.sql:ro
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
    vendor:
